### ISSUE TITLE
Rotation values

### ISSUE THREAD

**Issue by jonipokka** [AIRLegend/aitrack#160] opened 2022-08-17 17:00 UTC
**Describe the bug**
There seems to be a problem with roll values. I read from the patch notes that the values are capped at +-90 but the issue is that the default value that opentrack picks up is 90 and roll only works in one direction (changing offsets etc in opentrack do nothing).

Since the default value that aitrack seems to send is 90  when my head is straight, and the values are capped at +-90 cause the roll to only work one way. When I tilt my head right the roll works the value decreases 87....86....83... Etc in opentrack but when I tilt my head left the value stays at 90 and nothing happens.

**To Reproduce**
Start the program and follow instructions to use aitrack with opentrack. Default settings in opentrack.

**Expected behavior**
As my head seems to be recognized correctly since everything else works wonderfully (yaw, pitch, xyz) and aitrack draws the shape lines on my face correctly I expect the roll feature to work aswell in both directions and not only when rolling to one side.

**Environment (please complete the following information):**
 - Operating system version (Windows 10+ Version number):  Windows 10
 - Webcam model:  Logitech C920
 - AITrack version: 0.6.6

**Comment by searching46dof** [comment] 2022-08-20 19:37
I cofirmed the behavior.

Roll should be limited between 0.0 and 180.0 and v0.6.6 is coded as:
    // Limit roll between -90.0 and +90.0 
    if (face_data.rotation[2] >= 90.0)
        face_data.rotation[2] = 90.0;
    else if (face_data.rotation[2] <= -90.0)
        face_data.rotation[2] = -90.0;

I submitted the changes to restrict only yaw and pitch when they were initially exceeding +/-90deg which did not make sense since my face would be looking away from the camera. Roll did not have this issue and was not a problem since it would lose face tracking at +/-45deg from center (90deg).

I would recommend adding code to show the restrictions but leaving them #ifdef'd out for performance. It can be re-enabled if needed.
#if 0
    // Limit roll between -90.0 and +90.0 from center (=90deg)
    if (face_data.rotation[2] > 180.0)
        face_data.rotation[2] = 180.0;
    else if (face_data.rotation[2] < 0.0)
        face_data.rotation[2] = 0.0;
#endif

**Comment by AIRLegend** [comment] 2022-08-21 08:08
Yup. The problem is with the range. 

I think it's better to simply fix the range (set the clipping for roll to 0-180) instead of trusting the face detector will lose track at 45º as we could change the detectors in the future.

@searching46dof's proposal is the fix. I'll change it as soon as I can.

**Comment by AIRLegend** [comment] 2022-08-23 19:32
Fixed on #163

**Closed by AIRLegend** 2022-08-23 19:32 UTC
Labels: bug
